server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://182.61.17.140:3306/ctu_doc?verifyServerCertificate=false&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 182.61.17.140
    port: 6379
    password: lufangpu@123
  rabbitmq:
    host: 182.61.17.140
    port: 5672
    username: rabbitmq
    password: 123456
    virtual-host: /
    publisher-confirms: true
  thymeleaf:
     encoding: utf-8
     cache: false
     mode: HTML5
     prefix: classpath:/templates/
     suffix: .html